// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TaskMaster.Migrations
{
    [DbContext(typeof(TaskMasterDbContext))]
    partial class TaskMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskMaster.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hobbies"
                        });
                });

            modelBuilder.Entity("TaskMaster.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Finish the quarterly report",
                            DueDate = new DateTime(2024, 5, 21, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(286),
                            Priority = 1,
                            Title = "Complete Report",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Milk, Bread, Eggs",
                            DueDate = new DateTime(2024, 5, 19, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(336),
                            Priority = 2,
                            Title = "Buy Groceries",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Workout session at the gym",
                            DueDate = new DateTime(2024, 5, 20, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(345),
                            Priority = 3,
                            Title = "Go to the Gym",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Read 'The Great Gatsby'",
                            DueDate = new DateTime(2024, 5, 22, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(353),
                            Priority = 4,
                            Title = "Read Book",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Prepare slides for Monday meeting",
                            DueDate = new DateTime(2024, 5, 23, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(361),
                            Priority = 1,
                            Title = "Prepare Presentation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Catch up with mom",
                            DueDate = new DateTime(2024, 5, 24, 13, 4, 28, 157, DateTimeKind.Local).AddTicks(369),
                            Priority = 2,
                            Title = "Call Mom",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaskMaster.Models.TaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            TaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            TaskId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            TaskId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            TaskId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            TaskId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            TaskId = 6
                        });
                });

            modelBuilder.Entity("TaskMaster.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Password")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = 1234,
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = 2,
                            Password = 5678,
                            UserName = "JaneSmith"
                        },
                        new
                        {
                            Id = 3,
                            Password = 9012,
                            UserName = "AliceJohnson"
                        },
                        new
                        {
                            Id = 4,
                            Password = 3456,
                            UserName = "BobBrown"
                        });
                });

            modelBuilder.Entity("TaskMaster.Models.Task", b =>
                {
                    b.HasOne("TaskMaster.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskMaster.Models.TaskCategory", b =>
                {
                    b.HasOne("TaskMaster.Models.Category", "Category")
                        .WithMany("TaskCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskMaster.Models.Task", "Task")
                        .WithMany("TaskCategories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskMaster.Models.Category", b =>
                {
                    b.Navigation("TaskCategories");
                });

            modelBuilder.Entity("TaskMaster.Models.Task", b =>
                {
                    b.Navigation("TaskCategories");
                });

            modelBuilder.Entity("TaskMaster.Models.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
